<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $cars = [
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'blue',
                'status' => 1,
                'has_turbo' => true,
                'is_new' => false,
                'has_sunroof' => true,
                'kilometerage' => 1250,
                'duration' => 100,
                'price' => 240000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 2,
                'transmission_id' => 5,
                'brand_id' => 3,
                'car_model_id' => 2,
                'type_of_shop_id' => 2,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 25,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => true,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 100005,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 5,
                'transmission_id' => 2,
                'brand_id' => 1,
                'car_model_id' => 2,
                'type_of_shop_id' => 4,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 30,
                'color' => 'gold',
                'status' => 1,
                'has_turbo' => true,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 1253,
                'duration' => 10,
                'price' => 345000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 10004,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 2,
                'transmission_id' => 2,
                'brand_id' => 2,
                'car_model_id' => 4,
                'type_of_shop_id' => 5,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 10000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 1,
                'transmission_id' => 1,
                'brand_id' => 1,
                'car_model_id' => 1,
                'type_of_shop_id' => 1,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 10000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 1,
                'transmission_id' => 1,
                'brand_id' => 1,
                'car_model_id' => 1,
                'type_of_shop_id' => 1,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 10000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 1,
                'transmission_id' => 1,
                'brand_id' => 1,
                'car_model_id' => 1,
                'type_of_shop_id' => 1,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 10000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 1,
                'transmission_id' => 1,
                'brand_id' => 1,
                'car_model_id' => 1,
                'type_of_shop_id' => 1,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 10000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 1,
                'transmission_id' => 1,
                'brand_id' => 1,
                'car_model_id' => 1,
                'type_of_shop_id' => 1,
            ],
            [
                'production_date' => '2013-06-06',
                'engine_capacity' => 20,
                'color' => 'red',
                'status' => 1,
                'has_turbo' => false,
                'is_new' => false,
                'has_sunroof' => false,
                'kilometerage' => 125,
                'duration' => 10,
                'price' => 10000,
                'consumption' => 100,
                'top_speed' => 250,
                'dimensions' => 1000,
                'created_at' => now(),
                'updated_at' => now(),
                'fuel_type_id' => 1,
                'transmission_id' => 1,
                'brand_id' => 1,
                'car_model_id' => 1,
                'type_of_shop_id' => 1,
            ],
        ];

        DB::connection('mysql2')->table('cars')->insert($cars);
    }
}
